### ISSUE TITLE
Change Loan frequency to payment terms

### ISSUE THREAD

**Issue by ajqhw** [ajqportal/PEMCO-05-24-2017#6]
module under loan information ..under submenu loan frequency e change into name payments term and pls butangi ug 1 year till what number ang terms...

**Comment by ajqportal** [comment]
Alternative Payment Frequencies

Use this calculator to determine your payment or loan amount for different payment frequencies. You can make payments weekly, biweekly, semimonthly, monthly, bimonthly, quarterly, semiannually or annually. You can then examine your principal balances by payment, total of all payments made, and total interest paid.

**Comment by ajqportal** [comment]
Added loan payment terms.
